name: @Bootstedp/eslint-config Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: npm
        run: npm ci

      - name: Publish package on NPM registry
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
