name: "@Bootstedp/eslint-config Deploy"

on:
  push:
    paths:
      - 'eslint/**'
      - '.github/**'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

defaults:
  run:
    shell: bash
    working-directory: ./eslint

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: 
          yarn --frozen-lockfile 

      - name: Publish package on NPM registry
        run: 
          npm publish
